<?php

namespace App\Support;

/**
 * Danh mục loại nghỉ phép mặc định theo Bộ luật Lao động và Luật BHXH.
 *
 * Dùng cho migration tạo bảng, seeder đồng bộ lại, và làm nguồn dự phòng khi
 * bảng leave_types chưa tồn tại.
 */
class LeaveTypeDefaults
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function rows(): array
    {
        $rows = [
            [
                'code' => 'annual',
                'name' => 'Phép năm',
                'description' => 'Nghỉ phép hưởng nguyên lương, trừ vào số dư phép năm của nhân viên.',
                'annual_deduction' => 'yes',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'annual_balance',
                'quota_days' => null,
                'quota_note' => 'Theo số dư phép năm còn lại (cộng dần 1 ngày/tháng, tối đa 12 ngày/năm).',
                'enforce_quota' => true,
                'requires_document' => false,
                'document_hint' => null,
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'sky',
            ],
            [
                'code' => 'holiday',
                'name' => 'Nghỉ lễ, Tết',
                'description' => 'Ngày nghỉ lễ, Tết hưởng nguyên lương theo lịch nghỉ của Nhà nước.',
                'annual_deduction' => 'no',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'days_per_year',
                'quota_days' => 11,
                'quota_note' => '11 ngày/năm, hệ thống tự sinh theo danh mục ngày lễ.',
                'enforce_quota' => false,
                'requires_document' => false,
                'document_hint' => null,
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => true,
                'color' => 'red',
            ],
            [
                'code' => 'compensatory',
                'name' => 'Nghỉ bù',
                'description' => 'Nghỉ bù cho ngày đã làm thêm; không trừ phép năm mà trừ vào số dư ngày bù.',
                'annual_deduction' => 'compensatory',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'compensatory_balance',
                'quota_days' => null,
                'quota_note' => 'Theo số ngày bù đã tích lũy từ tăng ca / làm ngày nghỉ.',
                'enforce_quota' => false,
                'requires_document' => false,
                'document_hint' => null,
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'indigo',
            ],
            [
                'code' => 'wedding',
                'name' => 'Nghỉ kết hôn',
                'description' => 'Nghỉ việc riêng hưởng nguyên lương khi bản thân kết hôn.',
                'annual_deduction' => 'no',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'days_per_event',
                'quota_days' => 3,
                'quota_note' => '3 ngày cho mỗi lần kết hôn.',
                'enforce_quota' => true,
                'requires_document' => true,
                'document_hint' => 'Giấy đăng ký kết hôn hoặc thiệp cưới.',
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'fuchsia',
            ],
            [
                'code' => 'bereavement',
                'name' => 'Nghỉ hiếu (tang)',
                'description' => 'Nghỉ việc riêng hưởng nguyên lương khi có tang cha mẹ, vợ/chồng hoặc con.',
                'annual_deduction' => 'no',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'days_per_event',
                'quota_days' => 3,
                'quota_note' => '3 ngày cho mỗi lần chịu tang.',
                'enforce_quota' => true,
                'requires_document' => true,
                'document_hint' => 'Giấy báo tử / giấy chứng tử hoặc giấy tờ tang lễ.',
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'stone',
            ],
            [
                'code' => 'sick',
                'name' => 'Nghỉ ốm',
                'description' => 'Nghỉ ốm đau hưởng trợ cấp BHXH bằng 75% tiền lương đóng bảo hiểm.',
                'annual_deduction' => 'no',
                'salary_payer' => 'insurance',
                'salary_percent' => 75,
                'quota_type' => 'days_per_year',
                'quota_days' => 30,
                'quota_note' => 'Tối đa 30, 40 hoặc 60 ngày/năm tùy thời gian đã đóng BHXH.',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Giấy nghỉ ốm hưởng BHXH hoặc giấy ra viện.',
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'amber',
            ],
            [
                'code' => 'child_sick',
                'name' => 'Nghỉ con ốm',
                'description' => 'Nghỉ chăm con ốm hưởng chế độ BHXH.',
                'annual_deduction' => 'no',
                'salary_payer' => 'insurance',
                'salary_percent' => 75,
                'quota_type' => 'days_per_year',
                'quota_days' => 20,
                'quota_note' => '20 ngày/năm khi con dưới 3 tuổi; 15 ngày/năm khi con từ 3 đến dưới 7 tuổi.',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Giấy xác nhận con ốm của cơ sở y tế.',
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'orange',
            ],
            [
                'code' => 'prenatal_checkup',
                'name' => 'Nghỉ khám thai',
                'description' => 'Lao động nữ mang thai nghỉ đi khám thai, hưởng chế độ BHXH.',
                'annual_deduction' => 'no',
                'salary_payer' => 'insurance',
                'salary_percent' => 100,
                'quota_type' => 'times_per_pregnancy',
                'quota_days' => 5,
                'quota_note' => '5 lần/thai kỳ, mỗi lần 1 ngày (2 ngày nếu ở xa hoặc thai bệnh lý).',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Giấy khám thai của cơ sở y tế.',
                'gender_restriction' => 'female',
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'rose',
            ],
            [
                'code' => 'miscarriage',
                'name' => 'Nghỉ sảy thai, nạo hút thai',
                'description' => 'Nghỉ khi sảy thai, nạo, hút thai, thai chết lưu hoặc phá thai bệnh lý.',
                'annual_deduction' => 'no',
                'salary_payer' => 'insurance',
                'salary_percent' => 100,
                'quota_type' => 'days_per_event',
                'quota_days' => 50,
                'quota_note' => '10 đến 50 ngày tùy tuổi thai.',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Giấy tờ của bệnh viện (giấy ra viện, giấy chứng nhận nghỉ việc hưởng BHXH).',
                'gender_restriction' => 'female',
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'rose',
            ],
            [
                'code' => 'maternity',
                'name' => 'Nghỉ thai sản',
                'description' => 'Lao động nữ nghỉ sinh con, hưởng chế độ thai sản do BHXH chi trả.',
                'annual_deduction' => 'no',
                'salary_payer' => 'insurance',
                'salary_percent' => 100,
                'quota_type' => 'months_per_event',
                'quota_days' => 6,
                'quota_note' => '6 tháng; sinh đôi trở lên cộng thêm 1 tháng cho mỗi con.',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Giấy chứng sinh hoặc giấy khai sinh của con.',
                'gender_restriction' => 'female',
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'pink',
            ],
            [
                'code' => 'paternity',
                'name' => 'Nghỉ vợ sinh con',
                'description' => 'Lao động nam đang đóng BHXH nghỉ khi vợ sinh con.',
                'annual_deduction' => 'no',
                'salary_payer' => 'insurance',
                'salary_percent' => 100,
                'quota_type' => 'days_per_event',
                'quota_days' => 14,
                'quota_note' => '5, 7, 10 hoặc 14 ngày tùy trường hợp sinh thường, sinh mổ hay sinh đôi.',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Giấy chứng sinh hoặc giấy khai sinh của con.',
                'gender_restriction' => 'male',
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'cyan',
            ],
            [
                'code' => 'half_day',
                'name' => 'Nghỉ nửa ngày',
                'description' => 'Nghỉ buổi sáng hoặc buổi chiều trong một ngày làm việc, tính 0,5 ngày.',
                'annual_deduction' => 'no',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'none',
                'quota_days' => null,
                'quota_note' => 'Chỉ áp dụng trong một ngày làm việc, tính 0,5 ngày.',
                'enforce_quota' => false,
                'requires_document' => false,
                'document_hint' => null,
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'violet',
            ],
            [
                'code' => 'unpaid',
                'name' => 'Nghỉ không lương',
                'description' => 'Nghỉ không hưởng lương theo thỏa thuận với công ty.',
                'annual_deduction' => 'no',
                'salary_payer' => 'none',
                'salary_percent' => null,
                'quota_type' => 'agreement',
                'quota_days' => null,
                'quota_note' => 'Theo thỏa thuận với công ty.',
                'enforce_quota' => false,
                'requires_document' => false,
                'document_hint' => null,
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'slate',
            ],
            [
                'code' => 'business_trip',
                'name' => 'Đi công tác',
                'description' => 'Đi công tác theo phân công — hưởng nguyên lương và không tính là ngày nghỉ.',
                'annual_deduction' => 'no',
                'salary_payer' => 'company',
                'salary_percent' => 100,
                'quota_type' => 'none',
                'quota_days' => null,
                'quota_note' => 'Không giới hạn — không tính là ngày nghỉ.',
                'enforce_quota' => false,
                'requires_document' => true,
                'document_hint' => 'Quyết định hoặc văn bản cử đi công tác.',
                'gender_restriction' => null,
                'counts_as_leave' => false,
                'auto_generated' => false,
                'color' => 'teal',
            ],
            [
                'code' => 'other',
                'name' => 'Lý do khác',
                'description' => 'Trường hợp không thuộc các loại trên — người duyệt quyết định cách tính.',
                'annual_deduction' => 'approver',
                'salary_payer' => 'approver',
                'salary_percent' => null,
                'quota_type' => 'none',
                'quota_days' => null,
                'quota_note' => 'Do người duyệt quyết định.',
                'enforce_quota' => false,
                'requires_document' => false,
                'document_hint' => null,
                'gender_restriction' => null,
                'counts_as_leave' => true,
                'auto_generated' => false,
                'color' => 'slate',
            ],
        ];

        $sortOrder = 0;

        return array_map(function (array $row) use (&$sortOrder) {
            $sortOrder += 10;

            return [
                ...$row,
                'sort_order' => $sortOrder,
                'is_active' => true,
                'is_system' => true,
            ];
        }, $rows);
    }

    /**
     * @return list<string>
     */
    public static function codes(): array
    {
        return array_column(self::rows(), 'code');
    }
}
